
try:
    result = 4/0
    print(result)

except Exception as a :
    print(a)

print("Program End")

